# Generated by Django 3.2.13 on 2022-09-20 07:31

import auto_prefetch
import ckeditor.fields
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import softskillspace.utils.media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', auto_prefetch.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('bg_class', models.CharField(blank=True, choices=[('bg-danger', 'Danger'), ('bg-dark', 'Dark'), ('bg-dribbble', 'Dribbble'), ('bg-facebook', 'Facebook'), ('bg-google', 'Google'), ('bg-info', 'Info'), ('bg-instagram', 'Instagram'), ('bg-light', 'Light'), ('bg-linkedin', 'LinkedIn'), ('bg-orange', 'Orange'), ('bg-pinterest', 'Pinterest'), ('bg-primary', 'Primary'), ('bg-purple', 'Purple'), ('bg-secondary', 'Secondary'), ('bg-skype', 'Skype'), ('bg-success', 'Success'), ('bg-transparent', 'Transparent'), ('bg-twitter', 'Twitter'), ('bg-warning', 'Warning'), ('bg-white', 'White'), ('bg-youtube', 'YouTube')], max_length=20, null=True, verbose_name='background class')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=softskillspace.utils.media.get_image_upload_path)),
                ('blog', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
