# Generated by Django 3.2.13 on 2022-09-24 02:10

from django.db import migrations, models
import django_resized.forms
import softskillspace.utils.media


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to=softskillspace.utils.media.get_image_upload_path, verbose_name='Event banner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='online', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
